name = "invio-backend"
main = "dist/worker.mjs"
compatibility_date = "2024-12-18"
compatibility_flags = [ "nodejs_compat" ]
no_bundle = true
find_additional_modules = true

[build]
command = "npm install && node build.mjs"

[vars]
# Add your environment variables here

[[d1_databases]]
binding = "DB"
database_name = "invio-db"
database_id = "93f07b7d-281f-4728-a0f0-65b76cc9c61d"

[browser]
binding = "BROWSER"
